In [1]:
import numpy as np

In [2]:
array_1d = np.arange(1,11)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
array_2d = np.arange(1,10).reshape(3,3)
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
np_array = np.array([10,20,30,40,50])
print(np_array)

[10 20 30 40 50]


In [5]:
np_array_list = [array_1d, array_2d, np_array]

for arr in np_array_list:
    print(f"Array:\n{arr}\nShape: {arr.shape}\nData Type: {arr.dtype}\n")

Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data Type: int32

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int32

Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int32



In [6]:
a = np.array([10.20,30,40,50])
b = np.array([1,2,3,4])
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")
print(f"Exponentiation: {a ** b}")

Addition: [11.2 32.  43.  54. ]
Subtraction: [ 9.2 28.  37.  46. ]
Multiplication: [ 10.2  60.  120.  200. ]
Division: [10.2        15.         13.33333333 12.5       ]
Exponentiation: [1.02e+01 9.00e+02 6.40e+04 6.25e+06]


In [7]:
values = np.array([2, 4, 6, 8, 10])

print(f"Square Root: {np.sqrt(values)}")
print(f"Exponential: {np.exp(values)}")
print(f"Natural Logarithm: {np.log(values)}")
print(f"Sum of Elements: {np.sum(values)}")
print(f"Cumulative Sum: {np.cumsum(values)}")

Square Root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural Logarithm: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum of Elements: 30
Cumulative Sum: [ 2  6 12 20 30]


In [8]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(f"Row wise Sum: {np.sum(data, axis=1)}")
print(f"Column wise Sum: {np.sum(data, axis=0)}")
print(f"Minimum Value: {np.min(data)}")
print(f"Maximum Value: {np.max(data)}")
print(f"Mean Value: {np.mean(data)}")

Row wise Sum: [ 60 150 240]
Column wise Sum: [120 150 180]
Minimum Value: 10
Maximum Value: 90
Mean Value: 50.0


In [11]:
marks = np.array([78,85,90,66,72,88,95,60])
print(f"Mean: {np.mean(marks)}")
print(f"Median: {np.median(marks)}")
print(f"Variance: {np.var(marks)}")
print(f"Standard Deviation: {np.std(marks)}")
print(f"Minimum: {np.min(marks)}")
print(f"Maximum: {np.max(marks)}")
print(f"Range: {np.ptp(marks)}")
# sort the marks array
marks_sorted = np.sort(marks)
print(f"Sorted Marks: {marks_sorted}")
print(f"25th Percentile: {np.percentile(marks, 25)}")
print(f"50th Percentile (Median): {np.percentile(marks, 50)}")
print(f"75th Percentile: {np.percentile(marks, 75)}")
# how many students scored above 50 percentile
above_50_percentile = marks[marks > np.percentile(marks, 50)]
print(f"Number of Students above 50th Percentile: {len(above_50_percentile)}")

Mean: 79.25
Median: 81.5
Variance: 134.1875
Standard Deviation: 11.583932838203095
Minimum: 60
Maximum: 95
Range: 35
Sorted Marks: [60 66 72 78 85 88 90 95]
25th Percentile: 70.5
50th Percentile (Median): 81.5
75th Percentile: 88.5
Number of Students above 50th Percentile: 4


In [12]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
print(f"Total weekly sales: {np.sum(sales)}")
print(f"Mean weekly sales: {np.mean(sales)}")
print(f"Maximum weekly sales: {np.max(sales)}")
print(f"Minimum weekly sales: {np.min(sales)}")
print(f"Standard Deviation of weekly sales: {np.std(sales)}")
print(f"Sales above average: {sales[sales > np.mean(sales)]}")

Total weekly sales: 10700
Mean weekly sales: 1528.5714285714287
Maximum weekly sales: 2000
Minimum weekly sales: 900
Standard Deviation of weekly sales: 345.2298849598449
Sales above average: [2000 1800 1700 1600]
